name: Rebel Test1
favicon: null
layout_spectrum: 0.71601
typography_spectrum: 0.72649
title: Rebel Test1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cc0019'
    - '#ffffff'
    - '#ea8f97'
    - '#d84857'
    - '#f5cbcf'
  brandStrength: 0.3125
  lightness: 0.35641228989697993
  saturation: 0.5666666841134429
  rhythmicContrast: 0.78078218922019
purpose: []
